### ISSUE TITLE
MultibindingFragmentFactory and MultibindingViewModelFactoryProducer initialisation is leading to frozen frames.

### ISSUE THREAD

**Issue by sudchavan** [deliveryhero/whetstone#41] opened 2022-08-31 18:02 UTC
While investigating frozen frames for application, I came across lot of instances where MultibindingFragmentFactory and MultibindingViewModelFactoryProducer taking too much time to initialise things. Below are images which shows time in ms taken by these factories.

![Screenshot 2022-08-24 at 4 45 21 PM](https://user-images.githubusercontent.com/104982411/187747549-dae78354-1c4c-443d-8ace-6aef5cbbe076.png)

![Screenshot 2022-08-24 at 4 11 33 PM](https://user-images.githubusercontent.com/104982411/187747703-87a45340-aea1-494c-90a4-56d6f5ebcd61.png)

![Screenshot 2022-08-24 at 4 31 56 PM](https://user-images.githubusercontent.com/104982411/187747866-6298245b-c2bd-40be-bd3d-fd278598287d.png)

![Screenshot 2022-08-24 at 4 24 31 PM](https://user-images.githubusercontent.com/104982411/187748121-6dc3a807-9cf6-47e2-9b1d-4c7d7bb3a27d.png)

![Screenshot 2022-08-24 at 4 57 02 PM](https://user-images.githubusercontent.com/104982411/187748252-f3bfbd43-8d15-4fe0-a60d-58ab5fea8b27.png)

**Comment by helios66** [comment] 2022-09-26 10:31
Closing as "won't fix". This is because the cause of frozen frames is default android fragment initialisation behavior.

**Closed by helios66** 2022-09-26 10:31 UTC
